// Code generated by protoc-gen-go. DO NOT EDIT.
// source: greeter.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CinemahallRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SeatRows             int32    `protobuf:"varint,2,opt,name=seatRows,proto3" json:"seatRows,omitempty"`
	SeatRowCapacity      int32    `protobuf:"varint,3,opt,name=seatRowCapacity,proto3" json:"seatRowCapacity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CinemahallRequest) Reset()         { *m = CinemahallRequest{} }
func (m *CinemahallRequest) String() string { return proto.CompactTextString(m) }
func (*CinemahallRequest) ProtoMessage()    {}
func (*CinemahallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{0}
}

func (m *CinemahallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CinemahallRequest.Unmarshal(m, b)
}
func (m *CinemahallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CinemahallRequest.Marshal(b, m, deterministic)
}
func (m *CinemahallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CinemahallRequest.Merge(m, src)
}
func (m *CinemahallRequest) XXX_Size() int {
	return xxx_messageInfo_CinemahallRequest.Size(m)
}
func (m *CinemahallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CinemahallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CinemahallRequest proto.InternalMessageInfo

func (m *CinemahallRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CinemahallRequest) GetSeatRows() int32 {
	if m != nil {
		return m.SeatRows
	}
	return 0
}

func (m *CinemahallRequest) GetSeatRowCapacity() int32 {
	if m != nil {
		return m.SeatRowCapacity
	}
	return 0
}

type CinemahallResponse struct {
	Value                []*CinemahallRequest `protobuf:"bytes,1,rep,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CinemahallResponse) Reset()         { *m = CinemahallResponse{} }
func (m *CinemahallResponse) String() string { return proto.CompactTextString(m) }
func (*CinemahallResponse) ProtoMessage()    {}
func (*CinemahallResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{1}
}

func (m *CinemahallResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CinemahallResponse.Unmarshal(m, b)
}
func (m *CinemahallResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CinemahallResponse.Marshal(b, m, deterministic)
}
func (m *CinemahallResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CinemahallResponse.Merge(m, src)
}
func (m *CinemahallResponse) XXX_Size() int {
	return xxx_messageInfo_CinemahallResponse.Size(m)
}
func (m *CinemahallResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CinemahallResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CinemahallResponse proto.InternalMessageInfo

func (m *CinemahallResponse) GetValue() []*CinemahallRequest {
	if m != nil {
		return m.Value
	}
	return nil
}

type MovieRequest struct {
	MovieTitle           string   `protobuf:"bytes,1,opt,name=movieTitle,proto3" json:"movieTitle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MovieRequest) Reset()         { *m = MovieRequest{} }
func (m *MovieRequest) String() string { return proto.CompactTextString(m) }
func (*MovieRequest) ProtoMessage()    {}
func (*MovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{2}
}

func (m *MovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovieRequest.Unmarshal(m, b)
}
func (m *MovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovieRequest.Marshal(b, m, deterministic)
}
func (m *MovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovieRequest.Merge(m, src)
}
func (m *MovieRequest) XXX_Size() int {
	return xxx_messageInfo_MovieRequest.Size(m)
}
func (m *MovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MovieRequest proto.InternalMessageInfo

func (m *MovieRequest) GetMovieTitle() string {
	if m != nil {
		return m.MovieTitle
	}
	return ""
}

type MovieResponse struct {
	Value                []*MovieRequest `protobuf:"bytes,1,rep,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MovieResponse) Reset()         { *m = MovieResponse{} }
func (m *MovieResponse) String() string { return proto.CompactTextString(m) }
func (*MovieResponse) ProtoMessage()    {}
func (*MovieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{3}
}

func (m *MovieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovieResponse.Unmarshal(m, b)
}
func (m *MovieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovieResponse.Marshal(b, m, deterministic)
}
func (m *MovieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovieResponse.Merge(m, src)
}
func (m *MovieResponse) XXX_Size() int {
	return xxx_messageInfo_MovieResponse.Size(m)
}
func (m *MovieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MovieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MovieResponse proto.InternalMessageInfo

func (m *MovieResponse) GetValue() []*MovieRequest {
	if m != nil {
		return m.Value
	}
	return nil
}

type ReservationRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	ReservationId        int32    `protobuf:"varint,2,opt,name=reservationId,proto3" json:"reservationId,omitempty"`
	Show                 int32    `protobuf:"varint,3,opt,name=show,proto3" json:"show,omitempty"`
	Seats                int32    `protobuf:"varint,4,opt,name=seats,proto3" json:"seats,omitempty"`
	Reserved             bool     `protobuf:"varint,5,opt,name=reserved,proto3" json:"reserved,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReservationRequest) Reset()         { *m = ReservationRequest{} }
func (m *ReservationRequest) String() string { return proto.CompactTextString(m) }
func (*ReservationRequest) ProtoMessage()    {}
func (*ReservationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{4}
}

func (m *ReservationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReservationRequest.Unmarshal(m, b)
}
func (m *ReservationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReservationRequest.Marshal(b, m, deterministic)
}
func (m *ReservationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReservationRequest.Merge(m, src)
}
func (m *ReservationRequest) XXX_Size() int {
	return xxx_messageInfo_ReservationRequest.Size(m)
}
func (m *ReservationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReservationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReservationRequest proto.InternalMessageInfo

func (m *ReservationRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *ReservationRequest) GetReservationId() int32 {
	if m != nil {
		return m.ReservationId
	}
	return 0
}

func (m *ReservationRequest) GetShow() int32 {
	if m != nil {
		return m.Show
	}
	return 0
}

func (m *ReservationRequest) GetSeats() int32 {
	if m != nil {
		return m.Seats
	}
	return 0
}

func (m *ReservationRequest) GetReserved() bool {
	if m != nil {
		return m.Reserved
	}
	return false
}

type ReservationResponse struct {
	Value                []*ReservationRequest `protobuf:"bytes,1,rep,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ReservationResponse) Reset()         { *m = ReservationResponse{} }
func (m *ReservationResponse) String() string { return proto.CompactTextString(m) }
func (*ReservationResponse) ProtoMessage()    {}
func (*ReservationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{5}
}

func (m *ReservationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReservationResponse.Unmarshal(m, b)
}
func (m *ReservationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReservationResponse.Marshal(b, m, deterministic)
}
func (m *ReservationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReservationResponse.Merge(m, src)
}
func (m *ReservationResponse) XXX_Size() int {
	return xxx_messageInfo_ReservationResponse.Size(m)
}
func (m *ReservationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReservationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReservationResponse proto.InternalMessageInfo

func (m *ReservationResponse) GetValue() []*ReservationRequest {
	if m != nil {
		return m.Value
	}
	return nil
}

type ShowRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CinemaHall           string   `protobuf:"bytes,2,opt,name=cinemaHall,proto3" json:"cinemaHall,omitempty"`
	Movie                string   `protobuf:"bytes,3,opt,name=movie,proto3" json:"movie,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowRequest) Reset()         { *m = ShowRequest{} }
func (m *ShowRequest) String() string { return proto.CompactTextString(m) }
func (*ShowRequest) ProtoMessage()    {}
func (*ShowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{6}
}

func (m *ShowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowRequest.Unmarshal(m, b)
}
func (m *ShowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowRequest.Marshal(b, m, deterministic)
}
func (m *ShowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowRequest.Merge(m, src)
}
func (m *ShowRequest) XXX_Size() int {
	return xxx_messageInfo_ShowRequest.Size(m)
}
func (m *ShowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShowRequest proto.InternalMessageInfo

func (m *ShowRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ShowRequest) GetCinemaHall() string {
	if m != nil {
		return m.CinemaHall
	}
	return ""
}

func (m *ShowRequest) GetMovie() string {
	if m != nil {
		return m.Movie
	}
	return ""
}

type ShowResponse struct {
	Value                []*ShowRequest `protobuf:"bytes,1,rep,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ShowResponse) Reset()         { *m = ShowResponse{} }
func (m *ShowResponse) String() string { return proto.CompactTextString(m) }
func (*ShowResponse) ProtoMessage()    {}
func (*ShowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{7}
}

func (m *ShowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowResponse.Unmarshal(m, b)
}
func (m *ShowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowResponse.Marshal(b, m, deterministic)
}
func (m *ShowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowResponse.Merge(m, src)
}
func (m *ShowResponse) XXX_Size() int {
	return xxx_messageInfo_ShowResponse.Size(m)
}
func (m *ShowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShowResponse proto.InternalMessageInfo

func (m *ShowResponse) GetValue() []*ShowRequest {
	if m != nil {
		return m.Value
	}
	return nil
}

type UserRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{8}
}

func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (m *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(m, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UserResponse struct {
	Value                []*UserRequest `protobuf:"bytes,1,rep,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{9}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetValue() []*UserRequest {
	if m != nil {
		return m.Value
	}
	return nil
}

//Standard message for Requests
type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{10}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

//Standard message for Response
type Response struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{11}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*CinemahallRequest)(nil), "proto.CinemahallRequest")
	proto.RegisterType((*CinemahallResponse)(nil), "proto.CinemahallResponse")
	proto.RegisterType((*MovieRequest)(nil), "proto.MovieRequest")
	proto.RegisterType((*MovieResponse)(nil), "proto.MovieResponse")
	proto.RegisterType((*ReservationRequest)(nil), "proto.ReservationRequest")
	proto.RegisterType((*ReservationResponse)(nil), "proto.ReservationResponse")
	proto.RegisterType((*ShowRequest)(nil), "proto.ShowRequest")
	proto.RegisterType((*ShowResponse)(nil), "proto.ShowResponse")
	proto.RegisterType((*UserRequest)(nil), "proto.UserRequest")
	proto.RegisterType((*UserResponse)(nil), "proto.UserResponse")
	proto.RegisterType((*Request)(nil), "proto.Request")
	proto.RegisterType((*Response)(nil), "proto.Response")
}

func init() { proto.RegisterFile("greeter.proto", fileDescriptor_e585294ab3f34af5) }

var fileDescriptor_e585294ab3f34af5 = []byte{
	// 614 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcf, 0x6e, 0xda, 0x4e,
	0x10, 0x8e, 0x09, 0xfe, 0x61, 0x86, 0x00, 0xbf, 0x2c, 0x39, 0x38, 0x1c, 0x2a, 0x6a, 0xf5, 0xe0,
	0x5e, 0x68, 0x4b, 0x54, 0xa9, 0xaa, 0xda, 0x22, 0x9a, 0xa8, 0x34, 0x87, 0xf4, 0xe0, 0xb4, 0xbd,
	0xbb, 0x78, 0x14, 0xac, 0x1a, 0x4c, 0xbc, 0x4b, 0x50, 0x5e, 0xa4, 0xa7, 0x1e, 0x7a, 0xeb, 0xbb,
	0xf4, 0xa9, 0xaa, 0xfd, 0x67, 0xd6, 0xc5, 0x20, 0x91, 0x13, 0x33, 0xc3, 0xcc, 0xf7, 0x7d, 0x33,
	0x3b, 0x63, 0x68, 0xde, 0x64, 0x88, 0x0c, 0xb3, 0xfe, 0x22, 0x4b, 0x59, 0x4a, 0x6c, 0xf1, 0xe3,
	0xcd, 0xe0, 0xf8, 0x3c, 0x9e, 0xe3, 0x2c, 0x9c, 0x86, 0x49, 0x12, 0xe0, 0xed, 0x12, 0x29, 0x23,
	0x04, 0xaa, 0xf3, 0x70, 0x86, 0xae, 0xd5, 0xb3, 0xfc, 0x7a, 0x20, 0x6c, 0xd2, 0x05, 0x87, 0x62,
	0xc8, 0x82, 0x74, 0x45, 0xdd, 0x4a, 0xcf, 0xf2, 0xed, 0x20, 0xf7, 0x89, 0x0f, 0x6d, 0x65, 0x9f,
	0x87, 0x8b, 0x70, 0x12, 0xb3, 0x7b, 0xf7, 0x50, 0xa4, 0xfc, 0x1b, 0xf6, 0x2e, 0x80, 0x98, 0x74,
	0x74, 0x91, 0xce, 0x29, 0x92, 0x3e, 0xd8, 0x5f, 0xc3, 0x64, 0xc9, 0x09, 0x0f, 0xfd, 0xc6, 0xc0,
	0x95, 0x12, 0xfb, 0x1b, 0xc2, 0x02, 0x99, 0xe6, 0xf5, 0xe1, 0xe8, 0x2a, 0xbd, 0x8b, 0x51, 0xeb,
	0x7d, 0x04, 0x30, 0xe3, 0xfe, 0xe7, 0x98, 0x25, 0x5a, 0xb5, 0x11, 0xf1, 0x5e, 0x43, 0x53, 0xe5,
	0x2b, 0xc2, 0xa7, 0x45, 0xc2, 0x8e, 0x22, 0x34, 0x41, 0x35, 0xd7, 0x4f, 0x0b, 0x48, 0x80, 0x14,
	0xb3, 0xbb, 0x90, 0xc5, 0xe9, 0x5c, 0x53, 0x76, 0xc1, 0x59, 0x52, 0xcc, 0x3e, 0xad, 0xc7, 0x94,
	0xfb, 0xe4, 0x09, 0x34, 0xb3, 0x75, 0xc5, 0x65, 0xa4, 0xe6, 0x55, 0x0c, 0xf2, 0x21, 0xd3, 0x69,
	0xba, 0x52, 0x93, 0x12, 0x36, 0x39, 0x01, 0x9b, 0x4f, 0x8c, 0xba, 0x55, 0x11, 0x94, 0x0e, 0xe7,
	0x92, 0xa5, 0x18, 0xb9, 0x76, 0xcf, 0xf2, 0x9d, 0x20, 0xf7, 0xbd, 0x0f, 0xd0, 0x29, 0xa8, 0x53,
	0x0d, 0x3e, 0x2b, 0x36, 0x78, 0xaa, 0x1a, 0xdc, 0x6c, 0x44, 0xb7, 0x79, 0x0d, 0x8d, 0xeb, 0x69,
	0xba, 0xd2, 0xed, 0xb5, 0xa0, 0x12, 0x47, 0xa2, 0x31, 0x3b, 0xa8, 0xc4, 0x11, 0x9f, 0xf0, 0x44,
	0xbc, 0xc6, 0xc7, 0x30, 0x49, 0x44, 0x3f, 0xf5, 0xc0, 0x88, 0x70, 0xe1, 0x62, 0xde, 0xa2, 0x9b,
	0x7a, 0x20, 0x1d, 0xef, 0x15, 0x1c, 0x49, 0x50, 0xa5, 0xca, 0x2f, 0xaa, 0x22, 0x4a, 0x95, 0x41,
	0xac, 0xe5, 0x3c, 0x86, 0xc6, 0x17, 0x8a, 0xd9, 0x8e, 0x85, 0xe4, 0xe0, 0x32, 0x65, 0x37, 0xb8,
	0x01, 0xa3, 0xc1, 0xeb, 0x50, 0x53, 0x11, 0xef, 0x1d, 0x38, 0x39, 0x80, 0x0b, 0x35, 0xba, 0x9c,
	0x4c, 0x90, 0x52, 0xc1, 0xe3, 0x04, 0xda, 0xe5, 0xff, 0xcc, 0x90, 0xd2, 0xf0, 0x06, 0x55, 0xeb,
	0xda, 0x1d, 0xfc, 0xb1, 0x00, 0xd6, 0x6b, 0x4a, 0xde, 0x40, 0x73, 0x14, 0x45, 0x46, 0x60, 0xeb,
	0x2a, 0x77, 0xdb, 0xeb, 0x27, 0x11, 0xf4, 0xde, 0x01, 0x19, 0xc2, 0xff, 0x17, 0x98, 0x20, 0xc3,
	0x87, 0x02, 0xbc, 0x85, 0xd6, 0x18, 0xd9, 0x3a, 0x95, 0x92, 0x56, 0x9e, 0x24, 0x8b, 0x4e, 0x4b,
	0xe0, 0x74, 0xf9, 0xe0, 0xb7, 0x05, 0xb6, 0x38, 0x01, 0x32, 0x00, 0x67, 0x14, 0x45, 0xd2, 0x2e,
	0x3b, 0x8e, 0x32, 0xf2, 0x97, 0xd0, 0x90, 0xea, 0xf7, 0x2b, 0x3b, 0x83, 0xfa, 0x18, 0x99, 0xc8,
	0xda, 0x94, 0x7b, 0x52, 0x04, 0xc9, 0x95, 0xfe, 0xa8, 0x40, 0xc3, 0xd8, 0x65, 0x32, 0x84, 0xf6,
	0x55, 0xf8, 0x1d, 0xcd, 0xd0, 0xf6, 0x95, 0x2f, 0x53, 0x31, 0x82, 0x63, 0x29, 0xfe, 0xe1, 0x10,
	0xef, 0x0b, 0xdf, 0x89, 0xcb, 0xf9, 0xed, 0x32, 0xce, 0xee, 0xf7, 0xc4, 0x18, 0x42, 0x7b, 0x8c,
	0xcc, 0xc8, 0xdd, 0x1c, 0x49, 0xb7, 0x0c, 0x30, 0x1f, 0xcc, 0x2f, 0x0b, 0xaa, 0xfc, 0x9c, 0xc8,
	0x73, 0xa8, 0x8d, 0xa2, 0x48, 0x98, 0x25, 0x67, 0x56, 0xfe, 0x10, 0x20, 0x47, 0xb0, 0x4f, 0xd1,
	0x0b, 0x70, 0xc6, 0xc8, 0x78, 0xd2, 0xa6, 0xd2, 0x4e, 0x01, 0xa2, 0x20, 0x91, 0x1f, 0xa5, 0x92,
	0x28, 0xcc, 0x92, 0x63, 0xdd, 0x29, 0x71, 0x9f, 0x22, 0x29, 0x91, 0x27, 0x6d, 0x97, 0x68, 0x7e,
	0x48, 0xbc, 0x83, 0x6f, 0xff, 0x89, 0xe8, 0xd9, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd6, 0x72,
	0xd1, 0x4d, 0x33, 0x07, 0x00, 0x00,
}
